#!/usr/bin/env bash
#
# A wizard — walks a human through deploying techscout-ai to Render, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s etapas · cerca de %s minutos%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  Você dirige o navegador; este assistente diz exatamente o que fazer e\n' "$DIM"
  printf '  captura os valores de volta. Interrompa com Ctrl-C e rode de novo depois —\n'
  printf '  ele lembra dos valores já salvos.%s\n' "$RESET"
  pause "Pronto para começar?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Etapa %s/%s · %s%s  %s(~%s min restantes)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ abrindo%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "não consegui abrir o navegador — visite manualmente: $url"; fi
  } >/dev/null 2>&1 || warn "não consegui abrir o navegador — visite manualmente: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Pressione Enter para continuar}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter mantém o atual]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter mantém o atual]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ escreveu%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ definiu%s secret do GitHub %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("secret do GitHub $name (defina manualmente: gh secret set $name)")
  warn "pulei o secret $name — gh não está pronto; defina depois"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ definiu%s variável do GitHub %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("variável do GitHub $name")
  warn "pulei a variável $name — gh não está pronto; defina depois"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Deploy concluído%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "gravei ${#WRITTEN_ENV[@]} valor(es) em $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "defini ${#WRITTEN_SECRET[@]} secret(s): ${WRITTEN_SECRET[*]}"
  if [[ -n "${DEMO_URL:-}" ]]; then
    note "demo: $DEMO_URL"
  fi
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "ainda pendente (manual):"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — deploy do techscout-ai na Render.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
TOTAL_MINUTES=13

REPO="lucianoon/techscout-ai"

banner "Deploy do TechScout AI na Render"

# ── 1. Pré-requisitos ──────────────────────────────────────────────────────
stage "Pré-requisitos" 1
say "Vamos verificar o ambiente e capturar sua chave da OpenAI."

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  note "✓ gh autenticado"
else
  warn "gh CLI não autenticado — etapas do GitHub serão marcadas como pendentes."
fi

say ""
say "Você vai precisar da OPENAI_API_KEY (o app falha explícito sem ela)."
ask_secret OPENAI_API_KEY "Cole a OPENAI_API_KEY:"
while [[ -z "$OPENAI_API_KEY" ]]; do
  warn "a chave é obrigatória para o demo funcionar."
  ask_secret OPENAI_API_KEY "Cole a OPENAI_API_KEY:"
done
write_env OPENAI_API_KEY "$OPENAI_API_KEY"

# ── 2. Criar o serviço na Render ───────────────────────────────────────────
stage "Render — criar o serviço" 6
open_url "https://dashboard.render.com/select-repo?type=web"
step "Faça login na Render usando sua conta do GitHub."
step "Escolha o repositório ${REPO} na lista."
step "Se pedir o tipo, escolha 'Blueprint' (ele lê o render.yaml deste repo)."
step "Confirme o nome do serviço (sugestão: techscout-demo) e clique em Apply/Create."
note ""
note "O primeiro build demora ~4-5 min (imagem Docker com chromadb)."
note "Acompanhe os logs na tela da Render até ficar 'Live'."
pause "Deploy ficou 'Live'? Pressione Enter quando sim."

# ── 3. Chave no ambiente do serviço ────────────────────────────────────────
stage "Chave da OpenAI no serviço" 2
open_url "https://dashboard.render.com"
step "Abra o serviço techscout-demo."
step "Vá na aba 'Environment' → 'Add Environment Variable'."
step "Key: OPENAI_API_KEY   Value: cole a mesma chave de antes."
step "Clique em 'Save Changes' — isso dispara um redeploy rápido (~2 min)."
pause "Redeploy terminou? Pressione Enter quando sim."

# ── 4. Capturar a URL pública ──────────────────────────────────────────────
stage "URL pública" 1
step "No topo da página do serviço, copie a URL (.onrender.com)."
ask DEMO_URL "Cole a URL completa (com https://):"
DEMO_URL="${DEMO_URL%/}"   # remove barra final
while [[ ! "$DEMO_URL" =~ ^https:// ]]; do
  warn "a URL deve começar com https://"
  ask DEMO_URL "Cole a URL completa (com https://):"
  DEMO_URL="${DEMO_URL%/}"
done
write_env DEMO_URL "$DEMO_URL"
set_var DEMO_URL "$DEMO_URL"

# ── 5. Verificar a demo ────────────────────────────────────────────────────
stage "Verificação" 2
say "Testando o healthcheck do Streamlit em $DEMO_URL ..."
OK=""
for i in $(seq 1 10); do
  if curl -fsS --max-time 20 "$DEMO_URL/_stcore/health" >/dev/null 2>&1; then
    OK=1; break
  fi
  say "tentativa $i/10 — serviço ainda acordando… (aguardando 15s)"
  sleep 15
done
if [[ -n "$OK" ]]; then
  note "✓ healthcheck respondeu 200"
else
  warn "healthcheck não respondeu a tempo — confira os logs na Render antes de seguir."
fi
open_url "$DEMO_URL"
confirm "A interface do TechScout carregou no navegador?"

# ── 6. Keep-alive ──────────────────────────────────────────────────────────
stage "Manter a demo acordada" 1
say "O workflow 'keepalive.yml' faz ping a cada 10 min usando a variável DEMO_URL."
say "Ele só funciona se o gh estiver autenticado e a variável foi definida acima."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if gh workflow run keepalive.yml --repo "$REPO" 2>/dev/null; then
    note "✓ primeiro ping disparado manualmente"
  else
    SKIPPED+=("disparo manual do keepalive (rode: gh workflow run keepalive.yml --repo $REPO)")
    warn "não consegui disparar o workflow agora"
  fi
else
  SKIPPED+=("gh workflow run keepalive.yml --repo $REPO")
  warn "gh indisponível — dispare o workflow manualmente depois."
fi

finish
